# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windows.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1223, 895)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #000;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header.setStyleSheet("QFrame{\n"
"    border-bottom: 1px solid #000;\n"
"    background-color: #000;\n"
"}")
        self.main_header.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tittle_bar_container = QtWidgets.QFrame(self.main_header)
        self.tittle_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tittle_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar_container.setObjectName("tittle_bar_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tittle_bar_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toggle = QtWidgets.QFrame(self.tittle_bar_container)
        self.left_menu_toggle.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu_toggle.setStyleSheet("QFrame{\n"
"    background-color: #000;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px 10px;\n"
"    border: none;\n"
"    border-radius: 5px;    \n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 102, 255);\n"
"}\n"
"")
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_menu = QtWidgets.QPushButton(self.left_menu_toggle)
        self.btn_menu.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_menu.setText("")
        self.btn_menu.setIconSize(QtCore.QSize(36, 36))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_4.addWidget(self.btn_menu)
        self.horizontalLayout_5.addWidget(self.left_menu_toggle)
        self.tittle_bar = QtWidgets.QFrame(self.tittle_bar_container)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tittle_bar.setFont(font)
        self.tittle_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tittle_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar.setObjectName("tittle_bar")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tittle_bar)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tittle_label = QtWidgets.QLabel(self.tittle_bar)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tittle_label.setFont(font)
        self.tittle_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.tittle_label.setObjectName("tittle_label")
        self.verticalLayout_9.addWidget(self.tittle_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addWidget(self.tittle_bar)
        self.horizontalLayout_2.addWidget(self.tittle_bar_container)
        self.top_right_btns = QtWidgets.QFrame(self.main_header)
        self.top_right_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.top_right_btns.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 102, 255);\n"
"}\n"
"")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_minimize = QtWidgets.QPushButton(self.top_right_btns)
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("")
        self.btn_minimize.setText("")
        self.btn_minimize.setIconSize(QtCore.QSize(24, 24))
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_restore = QtWidgets.QPushButton(self.top_right_btns)
        self.btn_restore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_restore.setStyleSheet("")
        self.btn_restore.setText("")
        self.btn_restore.setIconSize(QtCore.QSize(24, 24))
        self.btn_restore.setObjectName("btn_restore")
        self.horizontalLayout_3.addWidget(self.btn_restore)
        self.btn_close = QtWidgets.QPushButton(self.top_right_btns)
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("")
        self.btn_close.setText("")
        self.btn_close.setIconSize(QtCore.QSize(24, 24))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.top_right_btns)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.left_side_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_side_menu.setStyleSheet("QFrame{\n"
"    background-color: #000;\n"
"}\n"
"QPushButton{\n"
"    padding: 20px 10px;\n"
"    border: none;\n"
"    border-left: 2px solid transparent;\n"
"    border-bottom: 2px solid transparent;\n"
"    border-radius: 5px;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 102, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(0,92,157);\n"
"    border-bottom: 2px solid rgb(255,165,24);\n"
"}\n"
"")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(7, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_menu_top_buttons = QtWidgets.QFrame(self.left_side_menu)
        self.left_menu_top_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_top_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_top_buttons.setObjectName("left_menu_top_buttons")
        self.formLayout = QtWidgets.QFormLayout(self.left_menu_top_buttons)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.btn_home = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.btn_home.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_home.setFont(font)
        self.btn_home.setStyleSheet("")
        self.btn_home.setObjectName("btn_home")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.btn_home)
        self.btn_venta = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.btn_venta.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.btn_venta.setFont(font)
        self.btn_venta.setStyleSheet("")
        self.btn_venta.setObjectName("btn_venta")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.btn_venta)
        self.btn_historial = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.btn_historial.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.btn_historial.setFont(font)
        self.btn_historial.setStyleSheet("")
        self.btn_historial.setObjectName("btn_historial")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.btn_historial)
        self.verticalLayout_2.addWidget(self.left_menu_top_buttons)
        self.btn_stock = QtWidgets.QPushButton(self.left_side_menu)
        self.btn_stock.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.btn_stock.setFont(font)
        self.btn_stock.setStyleSheet("")
        self.btn_stock.setObjectName("btn_stock")
        self.verticalLayout_2.addWidget(self.btn_stock)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_main_items = QtWidgets.QFrame(self.main_body)
        self.center_main_items.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_main_items.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_main_items.setObjectName("center_main_items")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.center_main_items)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_main_items)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.homeTopFrame = QtWidgets.QFrame(self.home_page)
        self.homeTopFrame.setStyleSheet("")
        self.homeTopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.homeTopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.homeTopFrame.setObjectName("homeTopFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.homeTopFrame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tableVentasDiarias = QtWidgets.QTableWidget(self.homeTopFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableVentasDiarias.sizePolicy().hasHeightForWidth())
        self.tableVentasDiarias.setSizePolicy(sizePolicy)
        self.tableVentasDiarias.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableVentasDiarias.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableVentasDiarias.setObjectName("tableVentasDiarias")
        self.tableVentasDiarias.setColumnCount(0)
        self.tableVentasDiarias.setRowCount(0)
        self.horizontalLayout_7.addWidget(self.tableVentasDiarias)
        self.verticalLayout_5.addWidget(self.homeTopFrame)
        self.homeBottomFrame = QtWidgets.QFrame(self.home_page)
        self.homeBottomFrame.setMinimumSize(QtCore.QSize(0, 280))
        self.homeBottomFrame.setMaximumSize(QtCore.QSize(16777215, 280))
        self.homeBottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.homeBottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.homeBottomFrame.setObjectName("homeBottomFrame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.homeBottomFrame)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tableStockHome = QtWidgets.QTableWidget(self.homeBottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableStockHome.sizePolicy().hasHeightForWidth())
        self.tableStockHome.setSizePolicy(sizePolicy)
        self.tableStockHome.setMinimumSize(QtCore.QSize(0, 0))
        self.tableStockHome.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableStockHome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableStockHome.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableStockHome.setObjectName("tableStockHome")
        self.tableStockHome.setColumnCount(2)
        self.tableStockHome.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableStockHome.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableStockHome.setHorizontalHeaderItem(1, item)
        self.tableStockHome.verticalHeader().setVisible(False)
        self.horizontalLayout_15.addWidget(self.tableStockHome)
        self.tableCantidadMensual = QtWidgets.QTableWidget(self.homeBottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableCantidadMensual.sizePolicy().hasHeightForWidth())
        self.tableCantidadMensual.setSizePolicy(sizePolicy)
        self.tableCantidadMensual.setMinimumSize(QtCore.QSize(250, 60))
        self.tableCantidadMensual.setMaximumSize(QtCore.QSize(250, 60))
        self.tableCantidadMensual.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableCantidadMensual.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCantidadMensual.setObjectName("tableCantidadMensual")
        self.tableCantidadMensual.setColumnCount(1)
        self.tableCantidadMensual.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableCantidadMensual.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableCantidadMensual.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableCantidadMensual.setItem(0, 0, item)
        self.tableCantidadMensual.verticalHeader().setVisible(False)
        self.horizontalLayout_15.addWidget(self.tableCantidadMensual, 0, QtCore.Qt.AlignTop)
        self.tableTotalMensual = QtWidgets.QTableWidget(self.homeBottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableTotalMensual.sizePolicy().hasHeightForWidth())
        self.tableTotalMensual.setSizePolicy(sizePolicy)
        self.tableTotalMensual.setMinimumSize(QtCore.QSize(230, 60))
        self.tableTotalMensual.setMaximumSize(QtCore.QSize(230, 60))
        self.tableTotalMensual.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableTotalMensual.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableTotalMensual.setObjectName("tableTotalMensual")
        self.tableTotalMensual.setColumnCount(1)
        self.tableTotalMensual.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableTotalMensual.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTotalMensual.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTotalMensual.setItem(0, 0, item)
        self.tableTotalMensual.verticalHeader().setVisible(False)
        self.horizontalLayout_15.addWidget(self.tableTotalMensual, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.homeBottomFrame)
        self.stackedWidget.addWidget(self.home_page)
        self.venta_page = QtWidgets.QWidget()
        self.venta_page.setObjectName("venta_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.venta_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.venta_frame = QtWidgets.QFrame(self.venta_page)
        self.venta_frame.setStyleSheet("")
        self.venta_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.venta_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.venta_frame.setObjectName("venta_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.venta_frame)
        self.verticalLayout_12.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.venta_frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2)
        self.tableCliente = QtWidgets.QTableWidget(self.venta_frame)
        self.tableCliente.setMinimumSize(QtCore.QSize(0, 60))
        self.tableCliente.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableCliente.setFont(font)
        self.tableCliente.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tableCliente.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableCliente.setAlternatingRowColors(False)
        self.tableCliente.setShowGrid(True)
        self.tableCliente.setWordWrap(True)
        self.tableCliente.setCornerButtonEnabled(True)
        self.tableCliente.setObjectName("tableCliente")
        self.tableCliente.setColumnCount(6)
        self.tableCliente.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableCliente.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCliente.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCliente.setItem(0, 5, item)
        self.tableCliente.horizontalHeader().setHighlightSections(True)
        self.tableCliente.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.tableCliente)
        self.label_3 = QtWidgets.QLabel(self.venta_frame)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.tableDetalle = QtWidgets.QTableWidget(self.venta_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableDetalle.setFont(font)
        self.tableDetalle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tableDetalle.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableDetalle.setTabKeyNavigation(True)
        self.tableDetalle.setAlternatingRowColors(True)
        self.tableDetalle.setObjectName("tableDetalle")
        self.tableDetalle.setColumnCount(3)
        self.tableDetalle.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableDetalle.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableDetalle.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableDetalle.setHorizontalHeaderItem(2, item)
        self.tableDetalle.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.tableDetalle)
        self.venta_totalFrame = QtWidgets.QFrame(self.venta_frame)
        self.venta_totalFrame.setStyleSheet("color: rgb(255, 255, 255);")
        self.venta_totalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.venta_totalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.venta_totalFrame.setObjectName("venta_totalFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.venta_totalFrame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_eliminar = QtWidgets.QPushButton(self.venta_totalFrame)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_eliminar.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_eliminar.setFont(font)
        self.btn_eliminar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_9.addWidget(self.btn_eliminar)
        self.btn_addItem = QtWidgets.QPushButton(self.venta_totalFrame)
        self.btn_addItem.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_addItem.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_addItem.setFont(font)
        self.btn_addItem.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.btn_addItem.setObjectName("btn_addItem")
        self.horizontalLayout_9.addWidget(self.btn_addItem)
        self.label_7 = QtWidgets.QLabel(self.venta_totalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.output_total = QtWidgets.QLabel(self.venta_totalFrame)
        self.output_total.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_total.setFont(font)
        self.output_total.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.output_total.setText("")
        self.output_total.setObjectName("output_total")
        self.horizontalLayout_9.addWidget(self.output_total)
        self.verticalLayout_12.addWidget(self.venta_totalFrame)
        self.venta_bottom_confirmFrame = QtWidgets.QFrame(self.venta_frame)
        self.venta_bottom_confirmFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.venta_bottom_confirmFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.venta_bottom_confirmFrame.setStyleSheet("")
        self.venta_bottom_confirmFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.venta_bottom_confirmFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.venta_bottom_confirmFrame.setObjectName("venta_bottom_confirmFrame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.venta_bottom_confirmFrame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_confirmar = QtWidgets.QCheckBox(self.venta_bottom_confirmFrame)
        self.checkBox_confirmar.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_confirmar.setFont(font)
        self.checkBox_confirmar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_confirmar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_confirmar.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_confirmar.setObjectName("checkBox_confirmar")
        self.horizontalLayout_10.addWidget(self.checkBox_confirmar)
        self.btn_aceptar = QtWidgets.QPushButton(self.venta_bottom_confirmFrame)
        self.btn_aceptar.setEnabled(False)
        self.btn_aceptar.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_aceptar.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_aceptar.setFont(font)
        self.btn_aceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_aceptar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.horizontalLayout_10.addWidget(self.btn_aceptar)
        self.verticalLayout_12.addWidget(self.venta_bottom_confirmFrame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.venta_frame)
        self.stackedWidget.addWidget(self.venta_page)
        self.historial_page = QtWidgets.QWidget()
        self.historial_page.setObjectName("historial_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.historial_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.historial_page)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.tophistorialFrame = QtWidgets.QFrame(self.historial_page)
        self.tophistorialFrame.setMinimumSize(QtCore.QSize(0, 65))
        self.tophistorialFrame.setMaximumSize(QtCore.QSize(16777215, 65))
        self.tophistorialFrame.setStyleSheet("")
        self.tophistorialFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tophistorialFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tophistorialFrame.setObjectName("tophistorialFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tophistorialFrame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.tophistorialFrame)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.comboBoxFiltroMes = QtWidgets.QComboBox(self.tophistorialFrame)
        self.comboBoxFiltroMes.setMinimumSize(QtCore.QSize(70, 30))
        self.comboBoxFiltroMes.setMaximumSize(QtCore.QSize(70, 30))
        self.comboBoxFiltroMes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxFiltroMes.setObjectName("comboBoxFiltroMes")
        self.horizontalLayout_6.addWidget(self.comboBoxFiltroMes)
        self.label_11 = QtWidgets.QLabel(self.tophistorialFrame)
        self.label_11.setMinimumSize(QtCore.QSize(0, 30))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.lineEditFiltroNombreHistorial = QtWidgets.QLineEdit(self.tophistorialFrame)
        self.lineEditFiltroNombreHistorial.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEditFiltroNombreHistorial.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEditFiltroNombreHistorial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditFiltroNombreHistorial.setText("")
        self.lineEditFiltroNombreHistorial.setObjectName("lineEditFiltroNombreHistorial")
        self.horizontalLayout_6.addWidget(self.lineEditFiltroNombreHistorial)
        self.label_12 = QtWidgets.QLabel(self.tophistorialFrame)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.lineEditFiltroRutHistorial = QtWidgets.QLineEdit(self.tophistorialFrame)
        self.lineEditFiltroRutHistorial.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEditFiltroRutHistorial.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEditFiltroRutHistorial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditFiltroRutHistorial.setObjectName("lineEditFiltroRutHistorial")
        self.horizontalLayout_6.addWidget(self.lineEditFiltroRutHistorial)
        self.tableCantidadMensual_Historial = QtWidgets.QTableWidget(self.tophistorialFrame)
        self.tableCantidadMensual_Historial.setMinimumSize(QtCore.QSize(250, 60))
        self.tableCantidadMensual_Historial.setMaximumSize(QtCore.QSize(250, 60))
        self.tableCantidadMensual_Historial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableCantidadMensual_Historial.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCantidadMensual_Historial.setObjectName("tableCantidadMensual_Historial")
        self.tableCantidadMensual_Historial.setColumnCount(1)
        self.tableCantidadMensual_Historial.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableCantidadMensual_Historial.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableCantidadMensual_Historial.setHorizontalHeaderItem(0, item)
        self.tableCantidadMensual_Historial.verticalHeader().setVisible(False)
        self.horizontalLayout_6.addWidget(self.tableCantidadMensual_Historial)
        self.tableTotalMensual_Historial = QtWidgets.QTableWidget(self.tophistorialFrame)
        self.tableTotalMensual_Historial.setMinimumSize(QtCore.QSize(250, 60))
        self.tableTotalMensual_Historial.setMaximumSize(QtCore.QSize(250, 60))
        self.tableTotalMensual_Historial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableTotalMensual_Historial.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableTotalMensual_Historial.setObjectName("tableTotalMensual_Historial")
        self.tableTotalMensual_Historial.setColumnCount(1)
        self.tableTotalMensual_Historial.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableTotalMensual_Historial.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTotalMensual_Historial.setHorizontalHeaderItem(0, item)
        self.tableTotalMensual_Historial.verticalHeader().setVisible(False)
        self.horizontalLayout_6.addWidget(self.tableTotalMensual_Historial)
        self.verticalLayout_7.addWidget(self.tophistorialFrame, 0, QtCore.Qt.AlignHCenter)
        self.centerhistorialFrame = QtWidgets.QFrame(self.historial_page)
        self.centerhistorialFrame.setStyleSheet("")
        self.centerhistorialFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centerhistorialFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centerhistorialFrame.setObjectName("centerhistorialFrame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.centerhistorialFrame)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tableHistorial = QtWidgets.QTableWidget(self.centerhistorialFrame)
        self.tableHistorial.setEnabled(True)
        self.tableHistorial.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableHistorial.setFont(font)
        self.tableHistorial.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableHistorial.setAutoFillBackground(False)
        self.tableHistorial.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.tableHistorial.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableHistorial.setAlternatingRowColors(False)
        self.tableHistorial.setShowGrid(True)
        self.tableHistorial.setGridStyle(QtCore.Qt.SolidLine)
        self.tableHistorial.setWordWrap(True)
        self.tableHistorial.setCornerButtonEnabled(True)
        self.tableHistorial.setObjectName("tableHistorial")
        self.tableHistorial.setColumnCount(5)
        self.tableHistorial.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(18)
        item.setFont(font)
        self.tableHistorial.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(18)
        item.setFont(font)
        self.tableHistorial.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(18)
        item.setFont(font)
        self.tableHistorial.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(18)
        item.setFont(font)
        self.tableHistorial.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(18)
        item.setFont(font)
        self.tableHistorial.setHorizontalHeaderItem(4, item)
        self.tableHistorial.horizontalHeader().setHighlightSections(True)
        self.tableHistorial.verticalHeader().setVisible(False)
        self.verticalLayout_15.addWidget(self.tableHistorial)
        self.verticalLayout_7.addWidget(self.centerhistorialFrame)
        self.bottomhistorialFrame = QtWidgets.QFrame(self.historial_page)
        self.bottomhistorialFrame.setMinimumSize(QtCore.QSize(0, 280))
        self.bottomhistorialFrame.setMaximumSize(QtCore.QSize(16777215, 280))
        self.bottomhistorialFrame.setStyleSheet("")
        self.bottomhistorialFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomhistorialFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomhistorialFrame.setObjectName("bottomhistorialFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.bottomhistorialFrame)
        self.verticalLayout_13.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tableHistorialVentaSeleccionada = QtWidgets.QTableWidget(self.bottomhistorialFrame)
        self.tableHistorialVentaSeleccionada.setMinimumSize(QtCore.QSize(0, 60))
        self.tableHistorialVentaSeleccionada.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableHistorialVentaSeleccionada.setFont(font)
        self.tableHistorialVentaSeleccionada.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableHistorialVentaSeleccionada.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableHistorialVentaSeleccionada.setObjectName("tableHistorialVentaSeleccionada")
        self.tableHistorialVentaSeleccionada.setColumnCount(8)
        self.tableHistorialVentaSeleccionada.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistorialVentaSeleccionada.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialVentaSeleccionada.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialVentaSeleccionada.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialVentaSeleccionada.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialVentaSeleccionada.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialVentaSeleccionada.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialVentaSeleccionada.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialVentaSeleccionada.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialVentaSeleccionada.setHorizontalHeaderItem(7, item)
        self.tableHistorialVentaSeleccionada.verticalHeader().setVisible(False)
        self.verticalLayout_13.addWidget(self.tableHistorialVentaSeleccionada)
        self.tableHistorialDetalleVentaSeleccionada = QtWidgets.QTableWidget(self.bottomhistorialFrame)
        self.tableHistorialDetalleVentaSeleccionada.setMinimumSize(QtCore.QSize(0, 150))
        self.tableHistorialDetalleVentaSeleccionada.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableHistorialDetalleVentaSeleccionada.setFont(font)
        self.tableHistorialDetalleVentaSeleccionada.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableHistorialDetalleVentaSeleccionada.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableHistorialDetalleVentaSeleccionada.setObjectName("tableHistorialDetalleVentaSeleccionada")
        self.tableHistorialDetalleVentaSeleccionada.setColumnCount(4)
        self.tableHistorialDetalleVentaSeleccionada.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialDetalleVentaSeleccionada.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialDetalleVentaSeleccionada.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialDetalleVentaSeleccionada.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        item.setFont(font)
        self.tableHistorialDetalleVentaSeleccionada.setHorizontalHeaderItem(3, item)
        self.tableHistorialDetalleVentaSeleccionada.verticalHeader().setVisible(False)
        self.verticalLayout_13.addWidget(self.tableHistorialDetalleVentaSeleccionada)
        self.eliminarVentaFrame = QtWidgets.QFrame(self.bottomhistorialFrame)
        self.eliminarVentaFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.eliminarVentaFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.eliminarVentaFrame.setStyleSheet("")
        self.eliminarVentaFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eliminarVentaFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eliminarVentaFrame.setObjectName("eliminarVentaFrame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.eliminarVentaFrame)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBoxConfirmarEliminarVenta = QtWidgets.QCheckBox(self.eliminarVentaFrame)
        self.checkBoxConfirmarEliminarVenta.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBoxConfirmarEliminarVenta.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxConfirmarEliminarVenta.setFont(font)
        self.checkBoxConfirmarEliminarVenta.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBoxConfirmarEliminarVenta.setObjectName("checkBoxConfirmarEliminarVenta")
        self.horizontalLayout_16.addWidget(self.checkBoxConfirmarEliminarVenta, 0, QtCore.Qt.AlignVCenter)
        self.btnEliminarVenta = QtWidgets.QPushButton(self.eliminarVentaFrame)
        self.btnEliminarVenta.setEnabled(False)
        self.btnEliminarVenta.setMinimumSize(QtCore.QSize(150, 30))
        self.btnEliminarVenta.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEliminarVenta.setFont(font)
        self.btnEliminarVenta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnEliminarVenta.setObjectName("btnEliminarVenta")
        self.horizontalLayout_16.addWidget(self.btnEliminarVenta, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_13.addWidget(self.eliminarVentaFrame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.bottomhistorialFrame)
        self.stackedWidget.addWidget(self.historial_page)
        self.stock_page = QtWidgets.QWidget()
        self.stock_page.setObjectName("stock_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.stock_page)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stock_frame = QtWidgets.QFrame(self.stock_page)
        self.stock_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stock_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stock_frame.setObjectName("stock_frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.stock_frame)
        self.verticalLayout_16.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_5 = QtWidgets.QLabel(self.stock_frame)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_16.addWidget(self.label_5)
        self.tableStock = QtWidgets.QTableWidget(self.stock_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        self.tableStock.setFont(font)
        self.tableStock.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableStock.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableStock.setTabKeyNavigation(True)
        self.tableStock.setAlternatingRowColors(True)
        self.tableStock.setObjectName("tableStock")
        self.tableStock.setColumnCount(3)
        self.tableStock.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(20)
        item.setFont(font)
        self.tableStock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(20)
        item.setFont(font)
        self.tableStock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(20)
        item.setFont(font)
        self.tableStock.setHorizontalHeaderItem(2, item)
        self.tableStock.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tableStock)
        self.label_9 = QtWidgets.QLabel(self.stock_frame)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(26)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_16.addWidget(self.label_9)
        self.tableActualizaStock = QtWidgets.QTableWidget(self.stock_frame)
        self.tableActualizaStock.setMinimumSize(QtCore.QSize(0, 60))
        self.tableActualizaStock.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableActualizaStock.setFont(font)
        self.tableActualizaStock.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tableActualizaStock.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableActualizaStock.setAlternatingRowColors(False)
        self.tableActualizaStock.setObjectName("tableActualizaStock")
        self.tableActualizaStock.setColumnCount(3)
        self.tableActualizaStock.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableActualizaStock.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        item.setFont(font)
        self.tableActualizaStock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        item.setFont(font)
        self.tableActualizaStock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        item.setFont(font)
        self.tableActualizaStock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableActualizaStock.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableActualizaStock.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableActualizaStock.setItem(0, 2, item)
        self.tableActualizaStock.horizontalHeader().setHighlightSections(True)
        self.tableActualizaStock.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tableActualizaStock)
        self.stock_center_confirmFrame = QtWidgets.QFrame(self.stock_frame)
        self.stock_center_confirmFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.stock_center_confirmFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stock_center_confirmFrame.setStyleSheet("")
        self.stock_center_confirmFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stock_center_confirmFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stock_center_confirmFrame.setObjectName("stock_center_confirmFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.stock_center_confirmFrame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_confirmarActualizaStock = QtWidgets.QCheckBox(self.stock_center_confirmFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_confirmarActualizaStock.setFont(font)
        self.checkBox_confirmarActualizaStock.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_confirmarActualizaStock.setObjectName("checkBox_confirmarActualizaStock")
        self.horizontalLayout_11.addWidget(self.checkBox_confirmarActualizaStock)
        self.btn_aceptarActualizaStock = QtWidgets.QPushButton(self.stock_center_confirmFrame)
        self.btn_aceptarActualizaStock.setEnabled(False)
        self.btn_aceptarActualizaStock.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_aceptarActualizaStock.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_aceptarActualizaStock.setFont(font)
        self.btn_aceptarActualizaStock.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_aceptarActualizaStock.setObjectName("btn_aceptarActualizaStock")
        self.horizontalLayout_11.addWidget(self.btn_aceptarActualizaStock)
        self.verticalLayout_16.addWidget(self.stock_center_confirmFrame, 0, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.stock_frame)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(26)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_16.addWidget(self.label_8, 0, QtCore.Qt.AlignBottom)
        self.tableLlavero = QtWidgets.QTableWidget(self.stock_frame)
        self.tableLlavero.setMinimumSize(QtCore.QSize(0, 60))
        self.tableLlavero.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.tableLlavero.setFont(font)
        self.tableLlavero.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tableLlavero.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableLlavero.setAlternatingRowColors(False)
        self.tableLlavero.setObjectName("tableLlavero")
        self.tableLlavero.setColumnCount(3)
        self.tableLlavero.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableLlavero.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        item.setFont(font)
        self.tableLlavero.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        item.setFont(font)
        self.tableLlavero.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        item.setFont(font)
        self.tableLlavero.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLlavero.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLlavero.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLlavero.setItem(0, 2, item)
        self.tableLlavero.horizontalHeader().setHighlightSections(True)
        self.tableLlavero.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tableLlavero)
        self.stock_bottom_confirmFrame = QtWidgets.QFrame(self.stock_frame)
        self.stock_bottom_confirmFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.stock_bottom_confirmFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stock_bottom_confirmFrame.setStyleSheet("")
        self.stock_bottom_confirmFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stock_bottom_confirmFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stock_bottom_confirmFrame.setObjectName("stock_bottom_confirmFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.stock_bottom_confirmFrame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_confirmarStock = QtWidgets.QCheckBox(self.stock_bottom_confirmFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_confirmarStock.setFont(font)
        self.checkBox_confirmarStock.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_confirmarStock.setObjectName("checkBox_confirmarStock")
        self.horizontalLayout_8.addWidget(self.checkBox_confirmarStock)
        self.btn_aceptarStock = QtWidgets.QPushButton(self.stock_bottom_confirmFrame)
        self.btn_aceptarStock.setEnabled(False)
        self.btn_aceptarStock.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_aceptarStock.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_aceptarStock.setFont(font)
        self.btn_aceptarStock.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_aceptarStock.setObjectName("btn_aceptarStock")
        self.horizontalLayout_8.addWidget(self.btn_aceptarStock)
        self.verticalLayout_16.addWidget(self.stock_bottom_confirmFrame, 0, QtCore.Qt.AlignHCenter)
        self.archivoFrame = QtWidgets.QFrame(self.stock_frame)
        self.archivoFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.archivoFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.archivoFrame.setStyleSheet("")
        self.archivoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.archivoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.archivoFrame.setObjectName("archivoFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.archivoFrame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame = QtWidgets.QFrame(self.archivoFrame)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setMinimumSize(QtCore.QSize(0, 30))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(26)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_17.addWidget(self.label_17)
        self.left = QtWidgets.QFrame(self.frame)
        self.left.setStyleSheet("")
        self.left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.left)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btnSeleccionarDestinoDB = QtWidgets.QPushButton(self.left)
        self.btnSeleccionarDestinoDB.setMinimumSize(QtCore.QSize(150, 30))
        self.btnSeleccionarDestinoDB.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSeleccionarDestinoDB.setFont(font)
        self.btnSeleccionarDestinoDB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnSeleccionarDestinoDB.setObjectName("btnSeleccionarDestinoDB")
        self.horizontalLayout_14.addWidget(self.btnSeleccionarDestinoDB)
        self.labelRutaDestinoDB = QtWidgets.QLabel(self.left)
        self.labelRutaDestinoDB.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelRutaDestinoDB.setText("")
        self.labelRutaDestinoDB.setObjectName("labelRutaDestinoDB")
        self.horizontalLayout_14.addWidget(self.labelRutaDestinoDB)
        self.btnExportarDB = QtWidgets.QPushButton(self.left)
        self.btnExportarDB.setEnabled(False)
        self.btnExportarDB.setMinimumSize(QtCore.QSize(120, 30))
        self.btnExportarDB.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnExportarDB.setFont(font)
        self.btnExportarDB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnExportarDB.setObjectName("btnExportarDB")
        self.horizontalLayout_14.addWidget(self.btnExportarDB)
        self.verticalLayout_17.addWidget(self.left)
        self.horizontalLayout_12.addWidget(self.frame)
        self.archivoRightFrame = QtWidgets.QFrame(self.archivoFrame)
        self.archivoRightFrame.setStyleSheet("")
        self.archivoRightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.archivoRightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.archivoRightFrame.setObjectName("archivoRightFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.archivoRightFrame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.archivoRightFrame)
        self.label_16.setMinimumSize(QtCore.QSize(0, 30))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(26)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.ImportarFrame = QtWidgets.QFrame(self.archivoRightFrame)
        self.ImportarFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.ImportarFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ImportarFrame.setStyleSheet("")
        self.ImportarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImportarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImportarFrame.setObjectName("ImportarFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.ImportarFrame)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnSeleccionarArchivoDB = QtWidgets.QPushButton(self.ImportarFrame)
        self.btnSeleccionarArchivoDB.setMinimumSize(QtCore.QSize(120, 30))
        self.btnSeleccionarArchivoDB.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSeleccionarArchivoDB.setFont(font)
        self.btnSeleccionarArchivoDB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnSeleccionarArchivoDB.setObjectName("btnSeleccionarArchivoDB")
        self.horizontalLayout_13.addWidget(self.btnSeleccionarArchivoDB)
        self.labelRutaArchivoDB = QtWidgets.QLabel(self.ImportarFrame)
        self.labelRutaArchivoDB.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelRutaArchivoDB.setText("")
        self.labelRutaArchivoDB.setObjectName("labelRutaArchivoDB")
        self.horizontalLayout_13.addWidget(self.labelRutaArchivoDB)
        self.checkBoxConfirmarNuevaDB = QtWidgets.QCheckBox(self.ImportarFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxConfirmarNuevaDB.setFont(font)
        self.checkBoxConfirmarNuevaDB.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBoxConfirmarNuevaDB.setObjectName("checkBoxConfirmarNuevaDB")
        self.horizontalLayout_13.addWidget(self.checkBoxConfirmarNuevaDB)
        self.btnImportarDB = QtWidgets.QPushButton(self.ImportarFrame)
        self.btnImportarDB.setEnabled(False)
        self.btnImportarDB.setMinimumSize(QtCore.QSize(120, 30))
        self.btnImportarDB.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnImportarDB.setFont(font)
        self.btnImportarDB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnImportarDB.setObjectName("btnImportarDB")
        self.horizontalLayout_13.addWidget(self.btnImportarDB)
        self.verticalLayout_10.addWidget(self.ImportarFrame)
        self.horizontalLayout_12.addWidget(self.archivoRightFrame)
        self.verticalLayout_16.addWidget(self.archivoFrame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_8.addWidget(self.stock_frame)
        self.stackedWidget.addWidget(self.stock_page)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.center_main_items)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMinimumSize(QtCore.QSize(0, 40))
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.main_footer.setStyleSheet("QFrame{\n"
"    background-color: #000;\n"
"    border-top-color: solid 1px #000;\n"
"}")
        self.main_footer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.main_footer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.main_footer)
        font = QtGui.QFont()
        font.setFamily("Scheherazade")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.main_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ASDASD"))
        self.tittle_label.setText(_translate("MainWindow", "LLAVEROS UNIVERSIDAD DE CHILE"))
        self.btn_home.setText(_translate("MainWindow", "HOME"))
        self.btn_venta.setText(_translate("MainWindow", "VENTA"))
        self.btn_historial.setText(_translate("MainWindow", "HISTORIAL"))
        self.btn_stock.setText(_translate("MainWindow", "STOCK"))
        item = self.tableStockHome.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Llavero"))
        item = self.tableStockHome.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.tableCantidadMensual.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nueva fila"))
        item = self.tableCantidadMensual.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cantidad ventas mensual"))
        __sortingEnabled = self.tableCantidadMensual.isSortingEnabled()
        self.tableCantidadMensual.setSortingEnabled(False)
        self.tableCantidadMensual.setSortingEnabled(__sortingEnabled)
        item = self.tableTotalMensual.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nueva fila"))
        item = self.tableTotalMensual.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Total mensual"))
        __sortingEnabled = self.tableTotalMensual.isSortingEnabled()
        self.tableTotalMensual.setSortingEnabled(False)
        self.tableTotalMensual.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Datos de Venta"))
        item = self.tableCliente.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nueva fila"))
        item = self.tableCliente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tableCliente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre Cliente"))
        item = self.tableCliente.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rut Cliente"))
        item = self.tableCliente.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Dirección Cliente"))
        item = self.tableCliente.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Teléfono Cliente"))
        item = self.tableCliente.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Entrega"))
        __sortingEnabled = self.tableCliente.isSortingEnabled()
        self.tableCliente.setSortingEnabled(False)
        self.tableCliente.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Detalle"))
        item = self.tableDetalle.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Llavero"))
        item = self.tableDetalle.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tableDetalle.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SubTotal"))
        self.btn_eliminar.setText(_translate("MainWindow", "Eliminar Fila"))
        self.btn_addItem.setText(_translate("MainWindow", "Agregar Llavero"))
        self.label_7.setText(_translate("MainWindow", "Total:"))
        self.checkBox_confirmar.setText(_translate("MainWindow", "Confirmar Datos"))
        self.btn_aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.label_4.setText(_translate("MainWindow", "Historial de ventas"))
        self.label_10.setText(_translate("MainWindow", "Filtro por mes: "))
        self.label_11.setText(_translate("MainWindow", "Filtrar Nombre: "))
        self.label_12.setText(_translate("MainWindow", "Filtrar Rut: "))
        item = self.tableCantidadMensual_Historial.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nueva fila"))
        item = self.tableCantidadMensual_Historial.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cantidad ventas mensual"))
        item = self.tableTotalMensual_Historial.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nueva fila"))
        item = self.tableTotalMensual_Historial.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Total mensual"))
        self.tableHistorial.setSortingEnabled(False)
        item = self.tableHistorial.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tableHistorial.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre Cliente"))
        item = self.tableHistorial.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Entrega"))
        item = self.tableHistorial.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cantitdad"))
        item = self.tableHistorial.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total"))
        item = self.tableHistorialVentaSeleccionada.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nueva fila"))
        item = self.tableHistorialVentaSeleccionada.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tableHistorialVentaSeleccionada.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre Cliente"))
        item = self.tableHistorialVentaSeleccionada.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rut Cliente"))
        item = self.tableHistorialVentaSeleccionada.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Direccion Cliente"))
        item = self.tableHistorialVentaSeleccionada.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Teléfono Cliente"))
        item = self.tableHistorialVentaSeleccionada.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Entrega"))
        item = self.tableHistorialVentaSeleccionada.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tableHistorialVentaSeleccionada.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Total"))
        item = self.tableHistorialDetalleVentaSeleccionada.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Llavero"))
        item = self.tableHistorialDetalleVentaSeleccionada.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tableHistorialDetalleVentaSeleccionada.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precio"))
        item = self.tableHistorialDetalleVentaSeleccionada.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Subtotal"))
        self.checkBoxConfirmarEliminarVenta.setText(_translate("MainWindow", "Confirmar"))
        self.btnEliminarVenta.setText(_translate("MainWindow", "Eliminar Venta"))
        self.label_5.setText(_translate("MainWindow", "Llaveros Existentes"))
        item = self.tableStock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre Llavero"))
        item = self.tableStock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Precio"))
        item = self.tableStock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stock Disponible"))
        self.label_9.setText(_translate("MainWindow", "Actualiza Llavero"))
        item = self.tableActualizaStock.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nueva fila"))
        item = self.tableActualizaStock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Llavero"))
        item = self.tableActualizaStock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nuevo Precio"))
        item = self.tableActualizaStock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nuevo Stock"))
        __sortingEnabled = self.tableActualizaStock.isSortingEnabled()
        self.tableActualizaStock.setSortingEnabled(False)
        self.tableActualizaStock.setSortingEnabled(__sortingEnabled)
        self.checkBox_confirmarActualizaStock.setText(_translate("MainWindow", "Confirmar Datos"))
        self.btn_aceptarActualizaStock.setText(_translate("MainWindow", "Aceptar"))
        self.label_8.setText(_translate("MainWindow", "Nuevo Llavero"))
        item = self.tableLlavero.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nueva fila"))
        item = self.tableLlavero.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tableLlavero.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Precio"))
        item = self.tableLlavero.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stock Inicial"))
        __sortingEnabled = self.tableLlavero.isSortingEnabled()
        self.tableLlavero.setSortingEnabled(False)
        self.tableLlavero.setSortingEnabled(__sortingEnabled)
        self.checkBox_confirmarStock.setText(_translate("MainWindow", "Confirmar Datos"))
        self.btn_aceptarStock.setText(_translate("MainWindow", "Aceptar"))
        self.label_17.setText(_translate("MainWindow", "Exportar DB"))
        self.btnSeleccionarDestinoDB.setText(_translate("MainWindow", "Seleccionar Destino"))
        self.btnExportarDB.setText(_translate("MainWindow", "Exportar DB"))
        self.label_16.setText(_translate("MainWindow", "Importar DB"))
        self.btnSeleccionarArchivoDB.setText(_translate("MainWindow", "Seleccionar DB"))
        self.checkBoxConfirmarNuevaDB.setText(_translate("MainWindow", "Confirmar Nueva DB"))
        self.btnImportarDB.setText(_translate("MainWindow", "Importar DB"))
        self.label_6.setText(_translate("MainWindow", "NO IMPORTA EL ESTADIO... NO IMPORTA EL MARCADOR.."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

